// Loads and types the site configuration from site.yaml.
// You normally do NOT edit this file — edit `src/data/site.yaml` instead.
// This module just parses that YAML and gives it TypeScript types.
import yaml from 'js-yaml';
// Vite inlines the raw file contents at build time (bundler-safe).
import raw from './site.yaml?raw';

export interface SiteLinks {
  github: string;
  scholar: string;
  linkedin: string;
  twitter: string;
  arxiv?: string;
}
export interface Identity {
  name: string;
  role: string;
  location: string;
  emailEnc: string;
  links: SiteLinks;
}
export interface TimelineEntry {
  when: string;
  what: string;
  detail?: string;
  links?: Array<{ label: string; href: string }>;
}
export interface EarlierProject {
  title: string;
  year: number;
  desc: string;
  url?: string;
}
export interface SiteData {
  identity: Identity;
  timeline: TimelineEntry[];
  software: { jaxopt: string };
  earlierProjects: EarlierProject[];
  seo: { defaultTitle: string; defaultDescription: string };
}

const site = yaml.load(raw) as SiteData;

export default site;
